### ISSUE TITLE
Ask_for_help_about_polar

### ISSUE THREAD

**Issue by 16201535wangshenyu** [fouzhe/Polar-Fuzz#4]
Dear fouzhe:

I am a graduate student of East China Normal University. I major in software engineering. Recently, I found one of your articles, titled Polar: Function Code Aware Fuzz Testing of ICS Protocol. I found it may help me achieve my goals in this research field. This would make a really positive contribution to my work.

First， Thank you very much for your help last time.   However, there are still some details about your paper that I would like to ask. In your paper, mentioned that you have fuzzed the libiec61850(MMS, GOOSE, SV).can you offer more details about that， eg， fuzzing all the protocols(MMS， SV, GOOSE), or just one of them? In the examples of the project, there are many examples of servers, which server do you fuzz? if you can  I promise they will be used only for research purposes. If you could give me some code details, I will be very grateful. I promise they will be used only for research purposes.

Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by fouzhe** [comment]
Hi, sorry for late.
In Section 5.3, we only selected the MMS of libiec61850 as the target, as is mention in the paper. And we used "server_example_basic_io" in the given project example as the fuzzing driver.
